parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: '5432'
    database_name: Base_SIG
    database_user: postgres
    database_password: Admindb123
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ee097918c71603ceced6e732bcb9657206d3b6b3
    database_path: null
